site_name: Resolução 21/2021 - CONSUP/IFRN
site_author: Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte
site_dir: /var/www/html/consup/rn/21/

theme:
  name: material
  language: pt

nav:
  - Início: index.md
  - Capítulos:
    - "Cap. 1: Apresentação": capitulo-1.md
    - "Cap. 2: Do ensino remoto emergencial e a composição dos módulos de ensino": capitulo-2.md
    - "Cap. 3: Da capacitação": capitulo-3.md
    - "Cap. 4: Do planejamento pedagógico": capitulo-4.md
    - "Cap. 5: Da avaliação": capitulo-5.md
    - "Cap. 6: Da reprovação": capitulo-6.md
    - "Cap. 7: Da certificação de conhecimentos": capitulo-7.md
    - "Cap. 8: Do acompanhamento das turmas": capitulo-8.md
    - "Cap. 9: Do acompanhamento de frequência": capitulo-9.md
    - "Cap. 10: Do atendimento aos estudantes com necessidades educacionais específicas": capitulo-10.md
    - "Cap. 11: Dos conselhos de classe": capitulo-11.md
    - "Cap. 12: Das reuniões pedagógicas": capitulo-12.md
    - "Cap. 13: Das reuniões de pais": capitulo-13.md
    - "Cap. 14: Do trancamento voluntário": capitulo-14.md
    - "Cap. 15: Das atividades externas": capitulo-15.md
    - "Cap. 16: Da participação dos estudantes em eventos": capitulo-16.md
    - "Cap. 17: Do calendário acadêmico": capitulo-17.md
    - "Cap. 18: Das disposições gerais e finais": capitulo-18.md

  - Artigos:
    - Art. 1: art-1.md
    - Art. 2: art-2.md
    - Art. 3: art-3.md
    - Art. 4: art-4.md
    - Art. 5: art-5.md
    - Art. 6: art-6.md
    - Art. 7: art-7.md
    - Art. 8: art-8.md
    - Art. 9: art-9.md
    - Art. 10: art-10.md
    - Art. 11: art-11.md
    - Art. 12: art-12.md
    - Art. 13: art-13.md
    - Art. 14: art-14.md
    - Art. 15: art-15.md
    - Art. 16: art-16.md
    - Art. 17: art-17.md
    - Art. 18: art-18.md
    - Art. 19: art-19.md
    - Art. 20: art-20.md
    - Art. 21: art-21.md
    - Art. 22: art-22.md
    - Art. 23: art-23.md
    - Art. 24: art-24.md
    - Art. 25: art-25.md
    - Art. 26: art-26.md
    - Art. 27: art-27.md
    - Art. 28: art-28.md
    - Art. 29: art-29.md
    - Art. 30: art-30.md
    - Art. 31: art-31.md
    - Art. 32: art-32.md
    - Art. 33: art-33.md
    - Art. 34: art-34.md
    - Art. 35: art-35.md
    - Art. 36: art-36.md
    - Art. 37: art-37.md
    - Art. 38: art-38.md
    - Art. 39: art-39.md
    - Art. 40: art-40.md
    - Art. 41: art-41.md
    - Art. 42: art-42.md
    - Art. 43: art-43.md
    - Art. 44: art-44.md
    - Art. 45: art-45.md
    - Art. 46: art-46.md

